name: Scheduled Netlify Deploy

on:
  schedule:
    - cron: '*/55 * * * *' # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger on demand revalidation for home page
        run: curl -X POST -d '{}' "carletonblueprint.org/api/revalidate/home"
      - name: Trigger on demand revalidation for projects page
        run: curl -X POST -d '{}' "carletonblueprint.org/api/revalidate/projects"
      - name: Trigger on demand revalidation for events page
        run: curl -X POST -d '{}' "carletonblueprint.org/api/revalidate/events"
      - name: Trigger on demand revalidation for students page
        run: curl -X POST -d '{}' "carletonblueprint.org/api/revalidate/students"
