name: Scheduled Revalidation

on:
  schedule:
    - cron: '*/55 * * * *' # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger on demand revalidation site wide
        run: curl -X POST -d '{}' "https://carletonblueprint.org/api/revalidate"
      - name: Visit the site
        run: curl -X GET "https://carletonblueprint.org"
